"""empty message

Revision ID: a7811bd120e5
Revises: 5f869df13361
Create Date: 2026-01-29 23:07:52.559552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7811bd120e5'
down_revision: Union[str, Sequence[str], None] = '5f869df13361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. tambah kolom, masih boleh NULL
    op.add_column(
        'email_verifications',
        sa.Column('name', sa.String(), nullable=True)
    )

    # 2. isi data lama supaya tidak NULL
    op.execute(
        "UPDATE email_verifications SET name = 'unknown'"
    )

    # 3. ubah jadi NOT NULL
    op.alter_column(
        'email_verifications',
        'name',
        nullable=False
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    op.drop_column('email_verifications', 'name')
    # ### end Alembic commands ###
