"""empty message

Revision ID: ea98daf8bcbe
Revises: 696f38e03142
Create Date: 2026-01-29 20:29:25.110504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea98daf8bcbe'
down_revision: Union[str, Sequence[str], None] = '696f38e03142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtasks', 'todo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtasks', 'todo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
